// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: database/databaseproxy.proto

package database

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueCode int32

const (
	ValueCode_INT32   ValueCode = 0
	ValueCode_INT64   ValueCode = 1
	ValueCode_FLOAT64 ValueCode = 2
	ValueCode_BOOL    ValueCode = 3
	ValueCode_BYTES   ValueCode = 4
	ValueCode_STRING  ValueCode = 5
	ValueCode_TIME    ValueCode = 6
	ValueCode_NULL    ValueCode = 7
)

// Enum value maps for ValueCode.
var (
	ValueCode_name = map[int32]string{
		0: "INT32",
		1: "INT64",
		2: "FLOAT64",
		3: "BOOL",
		4: "BYTES",
		5: "STRING",
		6: "TIME",
		7: "NULL",
	}
	ValueCode_value = map[string]int32{
		"INT32":   0,
		"INT64":   1,
		"FLOAT64": 2,
		"BOOL":    3,
		"BYTES":   4,
		"STRING":  5,
		"TIME":    6,
		"NULL":    7,
	}
)

func (x ValueCode) Enum() *ValueCode {
	p := new(ValueCode)
	*p = x
	return p
}

func (x ValueCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueCode) Descriptor() protoreflect.EnumDescriptor {
	return file_database_databaseproxy_proto_enumTypes[0].Descriptor()
}

func (ValueCode) Type() protoreflect.EnumType {
	return &file_database_databaseproxy_proto_enumTypes[0]
}

func (x ValueCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueCode.Descriptor instead.
func (ValueCode) EnumDescriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{0}
}

type Transaction_Status int32

const (
	Transaction_NOT_STARTED Transaction_Status = 0
	Transaction_ACTIVE      Transaction_Status = 1
	Transaction_COMMITTED   Transaction_Status = 2
	Transaction_ROLLED_BACK Transaction_Status = 3
	Transaction_UNKNOWN     Transaction_Status = 4
)

// Enum value maps for Transaction_Status.
var (
	Transaction_Status_name = map[int32]string{
		0: "NOT_STARTED",
		1: "ACTIVE",
		2: "COMMITTED",
		3: "ROLLED_BACK",
		4: "UNKNOWN",
	}
	Transaction_Status_value = map[string]int32{
		"NOT_STARTED": 0,
		"ACTIVE":      1,
		"COMMITTED":   2,
		"ROLLED_BACK": 3,
		"UNKNOWN":     4,
	}
)

func (x Transaction_Status) Enum() *Transaction_Status {
	p := new(Transaction_Status)
	*p = x
	return p
}

func (x Transaction_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_database_databaseproxy_proto_enumTypes[1].Descriptor()
}

func (Transaction_Status) Type() protoreflect.EnumType {
	return &file_database_databaseproxy_proto_enumTypes[1]
}

func (x Transaction_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_Status.Descriptor instead.
func (Transaction_Status) EnumDescriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{2, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_database_databaseproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{0}
}

type BeginTransactionConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Timeout          int64                  `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ReadOnly         bool                   `protobuf:"varint,2,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	ConnectionString string                 `protobuf:"bytes,3,opt,name=connectionString,proto3" json:"connectionString,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BeginTransactionConfig) Reset() {
	*x = BeginTransactionConfig{}
	mi := &file_database_databaseproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionConfig) ProtoMessage() {}

func (x *BeginTransactionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionConfig.ProtoReflect.Descriptor instead.
func (*BeginTransactionConfig) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{1}
}

func (x *BeginTransactionConfig) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *BeginTransactionConfig) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *BeginTransactionConfig) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Transaction_Status     `protobuf:"varint,2,opt,name=status,proto3,enum=dev.frndpovoa.project1.databaseproxy.proto.Transaction_Status" json:"status,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_database_databaseproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetStatus() Transaction_Status {
	if x != nil {
		return x.Status
	}
	return Transaction_NOT_STARTED
}

func (x *Transaction) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type ExecuteConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Query            string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Args             []*Value               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Timeout          int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ConnectionString string                 `protobuf:"bytes,4,opt,name=connectionString,proto3" json:"connectionString,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteConfig) Reset() {
	*x = ExecuteConfig{}
	mi := &file_database_databaseproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteConfig) ProtoMessage() {}

func (x *ExecuteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteConfig.ProtoReflect.Descriptor instead.
func (*ExecuteConfig) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteConfig) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteConfig) GetArgs() []*Value {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteConfig) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ExecuteConfig) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

type ExecuteTxConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ExecuteConfig *ExecuteConfig         `protobuf:"bytes,2,opt,name=executeConfig,proto3" json:"executeConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTxConfig) Reset() {
	*x = ExecuteTxConfig{}
	mi := &file_database_databaseproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTxConfig) ProtoMessage() {}

func (x *ExecuteTxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTxConfig.ProtoReflect.Descriptor instead.
func (*ExecuteTxConfig) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteTxConfig) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ExecuteTxConfig) GetExecuteConfig() *ExecuteConfig {
	if x != nil {
		return x.ExecuteConfig
	}
	return nil
}

type QueryConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Query            string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Args             []*Value               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Timeout          int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	FetchSize        int64                  `protobuf:"varint,4,opt,name=fetchSize,proto3" json:"fetchSize,omitempty"`
	ConnectionString string                 `protobuf:"bytes,5,opt,name=connectionString,proto3" json:"connectionString,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryConfig) Reset() {
	*x = QueryConfig{}
	mi := &file_database_databaseproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConfig) ProtoMessage() {}

func (x *QueryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConfig.ProtoReflect.Descriptor instead.
func (*QueryConfig) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{5}
}

func (x *QueryConfig) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryConfig) GetArgs() []*Value {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *QueryConfig) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *QueryConfig) GetFetchSize() int64 {
	if x != nil {
		return x.FetchSize
	}
	return 0
}

func (x *QueryConfig) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

type QueryTxConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	QueryConfig   *QueryConfig           `protobuf:"bytes,2,opt,name=queryConfig,proto3" json:"queryConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTxConfig) Reset() {
	*x = QueryTxConfig{}
	mi := &file_database_databaseproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTxConfig) ProtoMessage() {}

func (x *QueryTxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTxConfig.ProtoReflect.Descriptor instead.
func (*QueryTxConfig) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{6}
}

func (x *QueryTxConfig) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *QueryTxConfig) GetQueryConfig() *QueryConfig {
	if x != nil {
		return x.QueryConfig
	}
	return nil
}

type NextConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	QueryResultId string                 `protobuf:"bytes,2,opt,name=queryResultId,proto3" json:"queryResultId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextConfig) Reset() {
	*x = NextConfig{}
	mi := &file_database_databaseproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextConfig) ProtoMessage() {}

func (x *NextConfig) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextConfig.ProtoReflect.Descriptor instead.
func (*NextConfig) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{7}
}

func (x *NextConfig) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *NextConfig) GetQueryResultId() string {
	if x != nil {
		return x.QueryResultId
	}
	return ""
}

type ExecuteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowsAffected  int32                  `protobuf:"varint,1,opt,name=rowsAffected,proto3" json:"rowsAffected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	mi := &file_database_databaseproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteResult) GetRowsAffected() int32 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_database_databaseproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{9}
}

func (x *QueryResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryResult) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          []*Value               `protobuf:"bytes,1,rep,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_database_databaseproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{10}
}

func (x *Row) GetCols() []*Value {
	if x != nil {
		return x.Cols
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ValueCode              `protobuf:"varint,1,opt,name=code,proto3,enum=dev.frndpovoa.project1.databaseproxy.proto.ValueCode" json:"code,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_database_databaseproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{11}
}

func (x *Value) GetCode() ValueCode {
	if x != nil {
		return x.Code
	}
	return ValueCode_INT32
}

func (x *Value) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValueInt32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueInt32) Reset() {
	*x = ValueInt32{}
	mi := &file_database_databaseproxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueInt32) ProtoMessage() {}

func (x *ValueInt32) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueInt32.ProtoReflect.Descriptor instead.
func (*ValueInt32) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{12}
}

func (x *ValueInt32) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ValueInt64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueInt64) Reset() {
	*x = ValueInt64{}
	mi := &file_database_databaseproxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueInt64) ProtoMessage() {}

func (x *ValueInt64) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueInt64.ProtoReflect.Descriptor instead.
func (*ValueInt64) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{13}
}

func (x *ValueInt64) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ValueFloat64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueFloat64) Reset() {
	*x = ValueFloat64{}
	mi := &file_database_databaseproxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueFloat64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueFloat64) ProtoMessage() {}

func (x *ValueFloat64) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueFloat64.ProtoReflect.Descriptor instead.
func (*ValueFloat64) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{14}
}

func (x *ValueFloat64) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ValueBool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueBool) Reset() {
	*x = ValueBool{}
	mi := &file_database_databaseproxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueBool) ProtoMessage() {}

func (x *ValueBool) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueBool.ProtoReflect.Descriptor instead.
func (*ValueBool) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{15}
}

func (x *ValueBool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ValueString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueString) Reset() {
	*x = ValueString{}
	mi := &file_database_databaseproxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueString) ProtoMessage() {}

func (x *ValueString) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueString.ProtoReflect.Descriptor instead.
func (*ValueString) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{16}
}

func (x *ValueString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ValueTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueTime) Reset() {
	*x = ValueTime{}
	mi := &file_database_databaseproxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueTime) ProtoMessage() {}

func (x *ValueTime) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueTime.ProtoReflect.Descriptor instead.
func (*ValueTime) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{17}
}

func (x *ValueTime) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ValueNull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueNull) Reset() {
	*x = ValueNull{}
	mi := &file_database_databaseproxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueNull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueNull) ProtoMessage() {}

func (x *ValueNull) ProtoReflect() protoreflect.Message {
	mi := &file_database_databaseproxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueNull.ProtoReflect.Descriptor instead.
func (*ValueNull) Descriptor() ([]byte, []int) {
	return file_database_databaseproxy_proto_rawDescGZIP(), []int{18}
}

var File_database_databaseproxy_proto protoreflect.FileDescriptor

const file_database_databaseproxy_proto_rawDesc = "" +
	"\n" +
	"\x1cdatabase/databaseproxy.proto\x12*dev.frndpovoa.project1.databaseproxy.proto\"\a\n" +
	"\x05Empty\"z\n" +
	"\x16BeginTransactionConfig\x12\x18\n" +
	"\atimeout\x18\x01 \x01(\x03R\atimeout\x12\x1a\n" +
	"\breadOnly\x18\x02 \x01(\bR\breadOnly\x12*\n" +
	"\x10connectionString\x18\x03 \x01(\tR\x10connectionString\"\xdd\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12V\n" +
	"\x06status\x18\x02 \x01(\x0e2>.dev.frndpovoa.project1.databaseproxy.proto.Transaction.StatusR\x06status\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\"R\n" +
	"\x06Status\x12\x0f\n" +
	"\vNOT_STARTED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\r\n" +
	"\tCOMMITTED\x10\x02\x12\x0f\n" +
	"\vROLLED_BACK\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x04\"\xb2\x01\n" +
	"\rExecuteConfig\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12E\n" +
	"\x04args\x18\x02 \x03(\v21.dev.frndpovoa.project1.databaseproxy.proto.ValueR\x04args\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12*\n" +
	"\x10connectionString\x18\x04 \x01(\tR\x10connectionString\"\xcd\x01\n" +
	"\x0fExecuteTxConfig\x12Y\n" +
	"\vtransaction\x18\x01 \x01(\v27.dev.frndpovoa.project1.databaseproxy.proto.TransactionR\vtransaction\x12_\n" +
	"\rexecuteConfig\x18\x02 \x01(\v29.dev.frndpovoa.project1.databaseproxy.proto.ExecuteConfigR\rexecuteConfig\"\xce\x01\n" +
	"\vQueryConfig\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12E\n" +
	"\x04args\x18\x02 \x03(\v21.dev.frndpovoa.project1.databaseproxy.proto.ValueR\x04args\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12\x1c\n" +
	"\tfetchSize\x18\x04 \x01(\x03R\tfetchSize\x12*\n" +
	"\x10connectionString\x18\x05 \x01(\tR\x10connectionString\"\xc5\x01\n" +
	"\rQueryTxConfig\x12Y\n" +
	"\vtransaction\x18\x01 \x01(\v27.dev.frndpovoa.project1.databaseproxy.proto.TransactionR\vtransaction\x12Y\n" +
	"\vqueryConfig\x18\x02 \x01(\v27.dev.frndpovoa.project1.databaseproxy.proto.QueryConfigR\vqueryConfig\"\x8d\x01\n" +
	"\n" +
	"NextConfig\x12Y\n" +
	"\vtransaction\x18\x01 \x01(\v27.dev.frndpovoa.project1.databaseproxy.proto.TransactionR\vtransaction\x12$\n" +
	"\rqueryResultId\x18\x02 \x01(\tR\rqueryResultId\"3\n" +
	"\rExecuteResult\x12\"\n" +
	"\frowsAffected\x18\x01 \x01(\x05R\frowsAffected\"b\n" +
	"\vQueryResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\x04rows\x18\x02 \x03(\v2/.dev.frndpovoa.project1.databaseproxy.proto.RowR\x04rows\"L\n" +
	"\x03Row\x12E\n" +
	"\x04cols\x18\x01 \x03(\v21.dev.frndpovoa.project1.databaseproxy.proto.ValueR\x04cols\"f\n" +
	"\x05Value\x12I\n" +
	"\x04code\x18\x01 \x01(\x0e25.dev.frndpovoa.project1.databaseproxy.proto.ValueCodeR\x04code\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\"\n" +
	"\n" +
	"ValueInt32\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"\"\n" +
	"\n" +
	"ValueInt64\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"$\n" +
	"\fValueFloat64\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"!\n" +
	"\tValueBool\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"#\n" +
	"\vValueString\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\tValueTime\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\v\n" +
	"\tValueNull*c\n" +
	"\tValueCode\x12\t\n" +
	"\x05INT32\x10\x00\x12\t\n" +
	"\x05INT64\x10\x01\x12\v\n" +
	"\aFLOAT64\x10\x02\x12\b\n" +
	"\x04BOOL\x10\x03\x12\t\n" +
	"\x05BYTES\x10\x04\x12\n" +
	"\n" +
	"\x06STRING\x10\x05\x12\b\n" +
	"\x04TIME\x10\x06\x12\b\n" +
	"\x04NULL\x10\a2\xb2\v\n" +
	"\rDatabaseProxy\x12\x91\x01\n" +
	"\x10BeginTransaction\x12B.dev.frndpovoa.project1.databaseproxy.proto.BeginTransactionConfig\x1a7.dev.frndpovoa.project1.databaseproxy.proto.Transaction\"\x00\x12\x87\x01\n" +
	"\x11CommitTransaction\x127.dev.frndpovoa.project1.databaseproxy.proto.Transaction\x1a7.dev.frndpovoa.project1.databaseproxy.proto.Transaction\"\x00\x12\x89\x01\n" +
	"\x13RollbackTransaction\x127.dev.frndpovoa.project1.databaseproxy.proto.Transaction\x1a7.dev.frndpovoa.project1.databaseproxy.proto.Transaction\"\x00\x12\x81\x01\n" +
	"\aExecute\x129.dev.frndpovoa.project1.databaseproxy.proto.ExecuteConfig\x1a9.dev.frndpovoa.project1.databaseproxy.proto.ExecuteResult\"\x00\x12\x85\x01\n" +
	"\tExecuteTx\x12;.dev.frndpovoa.project1.databaseproxy.proto.ExecuteTxConfig\x1a9.dev.frndpovoa.project1.databaseproxy.proto.ExecuteResult\"\x00\x12{\n" +
	"\x05Query\x127.dev.frndpovoa.project1.databaseproxy.proto.QueryConfig\x1a7.dev.frndpovoa.project1.databaseproxy.proto.QueryResult\"\x00\x12\x7f\n" +
	"\aQueryTx\x129.dev.frndpovoa.project1.databaseproxy.proto.QueryTxConfig\x1a7.dev.frndpovoa.project1.databaseproxy.proto.QueryResult\"\x00\x12y\n" +
	"\x04Next\x126.dev.frndpovoa.project1.databaseproxy.proto.NextConfig\x1a7.dev.frndpovoa.project1.databaseproxy.proto.QueryResult\"\x00\x12}\n" +
	"\x0eCloseResultSet\x126.dev.frndpovoa.project1.databaseproxy.proto.NextConfig\x1a1.dev.frndpovoa.project1.databaseproxy.proto.Empty\"\x00\x12x\n" +
	"\x0eCloseStatement\x121.dev.frndpovoa.project1.databaseproxy.proto.Empty\x1a1.dev.frndpovoa.project1.databaseproxy.proto.Empty\"\x00\x12y\n" +
	"\x0fCloseConnection\x121.dev.frndpovoa.project1.databaseproxy.proto.Empty\x1a1.dev.frndpovoa.project1.databaseproxy.proto.Empty\"\x00B/Z(project1-database-proxy-golang/database;database\xa2\x02\x02DPb\x06proto3"

var (
	file_database_databaseproxy_proto_rawDescOnce sync.Once
	file_database_databaseproxy_proto_rawDescData []byte
)

func file_database_databaseproxy_proto_rawDescGZIP() []byte {
	file_database_databaseproxy_proto_rawDescOnce.Do(func() {
		file_database_databaseproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_databaseproxy_proto_rawDesc), len(file_database_databaseproxy_proto_rawDesc)))
	})
	return file_database_databaseproxy_proto_rawDescData
}

var file_database_databaseproxy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_database_databaseproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_database_databaseproxy_proto_goTypes = []any{
	(ValueCode)(0),                 // 0: dev.frndpovoa.project1.databaseproxy.proto.ValueCode
	(Transaction_Status)(0),        // 1: dev.frndpovoa.project1.databaseproxy.proto.Transaction.Status
	(*Empty)(nil),                  // 2: dev.frndpovoa.project1.databaseproxy.proto.Empty
	(*BeginTransactionConfig)(nil), // 3: dev.frndpovoa.project1.databaseproxy.proto.BeginTransactionConfig
	(*Transaction)(nil),            // 4: dev.frndpovoa.project1.databaseproxy.proto.Transaction
	(*ExecuteConfig)(nil),          // 5: dev.frndpovoa.project1.databaseproxy.proto.ExecuteConfig
	(*ExecuteTxConfig)(nil),        // 6: dev.frndpovoa.project1.databaseproxy.proto.ExecuteTxConfig
	(*QueryConfig)(nil),            // 7: dev.frndpovoa.project1.databaseproxy.proto.QueryConfig
	(*QueryTxConfig)(nil),          // 8: dev.frndpovoa.project1.databaseproxy.proto.QueryTxConfig
	(*NextConfig)(nil),             // 9: dev.frndpovoa.project1.databaseproxy.proto.NextConfig
	(*ExecuteResult)(nil),          // 10: dev.frndpovoa.project1.databaseproxy.proto.ExecuteResult
	(*QueryResult)(nil),            // 11: dev.frndpovoa.project1.databaseproxy.proto.QueryResult
	(*Row)(nil),                    // 12: dev.frndpovoa.project1.databaseproxy.proto.Row
	(*Value)(nil),                  // 13: dev.frndpovoa.project1.databaseproxy.proto.Value
	(*ValueInt32)(nil),             // 14: dev.frndpovoa.project1.databaseproxy.proto.ValueInt32
	(*ValueInt64)(nil),             // 15: dev.frndpovoa.project1.databaseproxy.proto.ValueInt64
	(*ValueFloat64)(nil),           // 16: dev.frndpovoa.project1.databaseproxy.proto.ValueFloat64
	(*ValueBool)(nil),              // 17: dev.frndpovoa.project1.databaseproxy.proto.ValueBool
	(*ValueString)(nil),            // 18: dev.frndpovoa.project1.databaseproxy.proto.ValueString
	(*ValueTime)(nil),              // 19: dev.frndpovoa.project1.databaseproxy.proto.ValueTime
	(*ValueNull)(nil),              // 20: dev.frndpovoa.project1.databaseproxy.proto.ValueNull
}
var file_database_databaseproxy_proto_depIdxs = []int32{
	1,  // 0: dev.frndpovoa.project1.databaseproxy.proto.Transaction.status:type_name -> dev.frndpovoa.project1.databaseproxy.proto.Transaction.Status
	13, // 1: dev.frndpovoa.project1.databaseproxy.proto.ExecuteConfig.args:type_name -> dev.frndpovoa.project1.databaseproxy.proto.Value
	4,  // 2: dev.frndpovoa.project1.databaseproxy.proto.ExecuteTxConfig.transaction:type_name -> dev.frndpovoa.project1.databaseproxy.proto.Transaction
	5,  // 3: dev.frndpovoa.project1.databaseproxy.proto.ExecuteTxConfig.executeConfig:type_name -> dev.frndpovoa.project1.databaseproxy.proto.ExecuteConfig
	13, // 4: dev.frndpovoa.project1.databaseproxy.proto.QueryConfig.args:type_name -> dev.frndpovoa.project1.databaseproxy.proto.Value
	4,  // 5: dev.frndpovoa.project1.databaseproxy.proto.QueryTxConfig.transaction:type_name -> dev.frndpovoa.project1.databaseproxy.proto.Transaction
	7,  // 6: dev.frndpovoa.project1.databaseproxy.proto.QueryTxConfig.queryConfig:type_name -> dev.frndpovoa.project1.databaseproxy.proto.QueryConfig
	4,  // 7: dev.frndpovoa.project1.databaseproxy.proto.NextConfig.transaction:type_name -> dev.frndpovoa.project1.databaseproxy.proto.Transaction
	12, // 8: dev.frndpovoa.project1.databaseproxy.proto.QueryResult.rows:type_name -> dev.frndpovoa.project1.databaseproxy.proto.Row
	13, // 9: dev.frndpovoa.project1.databaseproxy.proto.Row.cols:type_name -> dev.frndpovoa.project1.databaseproxy.proto.Value
	0,  // 10: dev.frndpovoa.project1.databaseproxy.proto.Value.code:type_name -> dev.frndpovoa.project1.databaseproxy.proto.ValueCode
	3,  // 11: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.BeginTransaction:input_type -> dev.frndpovoa.project1.databaseproxy.proto.BeginTransactionConfig
	4,  // 12: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.CommitTransaction:input_type -> dev.frndpovoa.project1.databaseproxy.proto.Transaction
	4,  // 13: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.RollbackTransaction:input_type -> dev.frndpovoa.project1.databaseproxy.proto.Transaction
	5,  // 14: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.Execute:input_type -> dev.frndpovoa.project1.databaseproxy.proto.ExecuteConfig
	6,  // 15: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.ExecuteTx:input_type -> dev.frndpovoa.project1.databaseproxy.proto.ExecuteTxConfig
	7,  // 16: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.Query:input_type -> dev.frndpovoa.project1.databaseproxy.proto.QueryConfig
	8,  // 17: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.QueryTx:input_type -> dev.frndpovoa.project1.databaseproxy.proto.QueryTxConfig
	9,  // 18: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.Next:input_type -> dev.frndpovoa.project1.databaseproxy.proto.NextConfig
	9,  // 19: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.CloseResultSet:input_type -> dev.frndpovoa.project1.databaseproxy.proto.NextConfig
	2,  // 20: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.CloseStatement:input_type -> dev.frndpovoa.project1.databaseproxy.proto.Empty
	2,  // 21: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.CloseConnection:input_type -> dev.frndpovoa.project1.databaseproxy.proto.Empty
	4,  // 22: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.BeginTransaction:output_type -> dev.frndpovoa.project1.databaseproxy.proto.Transaction
	4,  // 23: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.CommitTransaction:output_type -> dev.frndpovoa.project1.databaseproxy.proto.Transaction
	4,  // 24: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.RollbackTransaction:output_type -> dev.frndpovoa.project1.databaseproxy.proto.Transaction
	10, // 25: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.Execute:output_type -> dev.frndpovoa.project1.databaseproxy.proto.ExecuteResult
	10, // 26: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.ExecuteTx:output_type -> dev.frndpovoa.project1.databaseproxy.proto.ExecuteResult
	11, // 27: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.Query:output_type -> dev.frndpovoa.project1.databaseproxy.proto.QueryResult
	11, // 28: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.QueryTx:output_type -> dev.frndpovoa.project1.databaseproxy.proto.QueryResult
	11, // 29: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.Next:output_type -> dev.frndpovoa.project1.databaseproxy.proto.QueryResult
	2,  // 30: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.CloseResultSet:output_type -> dev.frndpovoa.project1.databaseproxy.proto.Empty
	2,  // 31: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.CloseStatement:output_type -> dev.frndpovoa.project1.databaseproxy.proto.Empty
	2,  // 32: dev.frndpovoa.project1.databaseproxy.proto.DatabaseProxy.CloseConnection:output_type -> dev.frndpovoa.project1.databaseproxy.proto.Empty
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_database_databaseproxy_proto_init() }
func file_database_databaseproxy_proto_init() {
	if File_database_databaseproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_databaseproxy_proto_rawDesc), len(file_database_databaseproxy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_databaseproxy_proto_goTypes,
		DependencyIndexes: file_database_databaseproxy_proto_depIdxs,
		EnumInfos:         file_database_databaseproxy_proto_enumTypes,
		MessageInfos:      file_database_databaseproxy_proto_msgTypes,
	}.Build()
	File_database_databaseproxy_proto = out.File
	file_database_databaseproxy_proto_goTypes = nil
	file_database_databaseproxy_proto_depIdxs = nil
}
